<body>
    <h1>Register your's url for webhook</h1>
    <form action="" method="post">
    <input type="text" name="name" placeholder="Enter Your name">
    <input type="url" name="url" placeholder="Enter url to recieve webhook response"><br>
    <input type="text" name="token" placeholder="Enter token for your authentication"><br>
    <input type="checkbox"  name="events[]" value="when product is added">
    <label for=""> When product is added</label><br>
    <input type="checkbox"  name="events[]" value="when product is updated">
    <label for=""> When Product is updated</label><br>
    <br>
    <input type="submit" value="Submit">
    </form>
</body>