<body>
    <div class="container-fluid">
        <div class="mt-5 w-50 m-auto border" >
            <!-- <p><ion-icon name="person"></ion-icon></p> -->
            <div for="icons">
                <a href="/user/login"><ion-icon name="log-in" style="color:brown;font-size:64px;"></ion-icon></a>

            </div>
            <form class="d-flex flex-column shadow-lg p-3" action="" method="post">
                <input type="text" class=" p-2 rounded-pill border-info text-center fw-bolder" name="name" placeholder="Enter Your Name" >
                <input type="text" class="mt-2 p-2 rounded-pill border-info text-center fw-bolder" name="role" placeholder="Enter Your Role" >
                <input type="email" class=" mt-2 p-2 border-info rounded-pill text-center fw-bolder" name="email" placeholder="Enter Your Email" >
                <input type="password" class=" mt-2 p-2 border-info rounded-pill text-center fw-bolder" name="password" placeholder="Enter Your Password" >
                <button class="btn btn-info mt-2 rounded-pill fw-bolder">Submit</button>
            </form>

        </div>

    </div>
</body>