<body>
    <div>
        <!-- <a class="btn btn-danger" href="/test/getToken">GET TOKEN</a> -->
        <a class="btn btn-danger" href="/test/getProducts">GET PRODUCTS</a>
        <a class="btn btn-danger" href="/test/productSearch">SEARCH PRODUCT</a>
        <a class="btn btn-danger" href="/test/placeOrder">PLACE ORDER</a>
        <a class="btn btn-danger" href="/test/updateOrder">UPDATE ORDER</a>
    </div>
</body>